version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/brainbattle?authSource=admin
      - JWT_SECRET=brainbattle_super_secret_key_2024_change_this_in_production
      - SESSION_SECRET=brainbattle_session_secret_key_change_in_production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./brainbattle
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: unless-stopped

volumes:
  mongodb_data: